### ISSUE TITLE
Dashboard view and button in exercises not available

### ISSUE THREAD

**Issue by brianstinehart** [sjbylo/lab-ocp4#7]
Hi Steve, just caught that the dashboard view is unavailable to students but gets referenced a couple times in the exercises. There is currently no way that I can find for them to access this view and see utilisation info. It seems to be an RBAC issue where the logged in user doesn't have access to these views.

- Exercise 1. Get started with OpenShift: 

The status of your project can be seen here:

Status
Click on the Dashboard button to see your resource usage in your project. As you have just started the workshop you are using nothing, so it shows 0% utilization for CPU and Memory.

- Exercise 5. Run the Source:

Finally, take a look at the resource utilization in the Console:

Status
Click on the Dashboard button to see your resource usage in your project.

**Comment by sjbylo** [comment]
Thanks for the heads up.   It seems a normal user does not get to see that status info, whereas an admin user does, CMIIW.  I will have to remove these sections. They are short and can be easily deleted.

**Comment by sjbylo** [comment]
I removed both those sections in Exercise 1 and 5.   Thanks.
